#!/bin/sh
git am ../patch/0001-x86-provide-CONFIG_BUILD_ROM.patch
git am ../patch/0001-part-move-efi_guid_t.patch
git am ../patch/0001-efi_loader-fix-typo-in-include-efi.h.patch
git am ../patch/0001-efi_loader-fix-bug-in-efi_add_known_memory.patch

git  am ../patch/0001-efi_loader-provide-comment-for-protocol-GUIDs.patch

# EFI event services
git am ../patch/0001-efi_loader-allow-return-value-in-EFI_CALL.patch
git am ../patch/0001-efi_selftest-provide-an-EFI-selftest-application.patch
git am ../patch/0001-test-py-add-a-test-calling-the-EFI-selftest.patch
git am ../patch/0001-efi_loader-implement-queueing-of-the-notification-fu.patch
git am ../patch/0001-efi_loader-efi_set_timer-reset-signaled-state.patch
git am ../patch/0001-efi_selftest-provide-unit-test-for-event-services.patch
git am ../patch/0001-efi_loader-implement-task-priority-level-TPL.patch
git am ../patch/0001-efi_selftest-test-task-priority-levels.patch
git am ../patch/0001-efi_loader-notify-when-ExitBootServices-is-invoked.patch
git am ../patch/0001-efi_selftest-check-notification-of-ExitBootServices.patch

# Prepare EFI selftest
git am ../patch/0001-x86-qemu-enable-EFI-selftest.patch
git am ../patch/0001-vexpress_ca15_tc2_defconfig-build-EFI.patch

exit
# git am ../patch/0001-efi_loader-move-efi_guid_t-typedef-to-efi.h.patch
git am ../patch/0001-efi_loader-helloworld.c-remove-superfluous-include.patch

# Fix building u-boot.rom for qemu-x86_64_defconfig
git am ../patch/0001-spl-u-boot-spl-nodtb.bin-remove-.got-and-.got.plt-se.patch

git am ../patch/0001-efi_loader-fix-building-of-helloworld.efi-on-x86_64.patch


# git am ../patch/0001-tools-elf2efi-add-tool-elf2efi.patch
# git am ../patch/0001-elf2efi.c-ignore-R_ARM_V4BX.patch
# git am ../patch/0001-efi_loader-allow-multiple-source-files-for-EFI-apps.patch
# git am ../patch/0001-efi_selftest-provide-an-EFI-selftest-application.patch

# EFI protocol services
git am ../patch/0001-efi_loader-get-rid-of-upper-case-type-UINTN.patch
git am ../patch/0001-efi_loader-ProtocolsPerHandle-argument-ProtocolBuffe.patch
git am ../patch/0001-efi_loader-arguments-of-efi_locate_handle-_buffer.patch
git am ../patch/0001-efi_loader-capitalize-EFI_LOCATE_SEARCH_TYPE-values.patch
git am ../patch/0001-efi_loader-rework-efi_locate_handle.patch
git am ../patch/0001-efi_loader-rework-efi_search_obj.patch
git am ../patch/0001-efi_loader-new-function-efi_search_protocol.patch
git am ../patch/0001-efi_loader-simplify-efi_install_protocol_interface.patch
git am ../patch/0001-efi_loader-allow-creating-new-handles.patch
git am ../patch/0001-efi_loader-simplify-efi_uninstall_protocol_interface.patch
git am ../patch/0001-efi_loader-support-16-protocols-per-efi_object.patch
git am ../patch/0001-efi_loader-open_info-in-OpenProtocol.patch
git am ../patch/0001-efi_loader-open_info-in-CloseProtocol.patch
git am ../patch/0002-efi_loader-implement-OpenProtocolInformation.patch
git am ../patch/0001-efi_loader-non-static-efi_open_protocol-efi_close_pr.patch
git am ../patch/0001-efi_loader-pass-GUIDs-as-const-efi_guid_t.patch
git am ../patch/0001-efi_loader-implement-ConnectController.patch
git am ../patch/0001-efi_loader-implement-DisconnectController.patch
git am ../patch/0001-efi_selftest-test-protocol-handler-services.patch

# EFI Network
git am ../patch/0001-efi_loader-efi_net-hwaddr_size-6.patch
git am ../patch/0001-efi_net-return-EFI_UNSUPPORTED-where-appropriate.patch
git am ../patch/0001-efi_loader-correct-bits-of-receive_filters-bit-mask.patch
git am ../patch/0001-efi_loader-use-events-for-efi_net_receive.patch
git am ../patch/0001-efi_loader-fix-efi_net_get_status.patch

# Image loading
git am ../patch/0001-efi_loader-set-parent-handle-in-efi_load_image.patch

# Implement Watchdog
git am ../patch/0001-efi_loader-implement-SetWatchdogTimer.patch

# The patches below have dependencies that yet have to be merged.
exit

# Print GUIDs
git am ../patch/0001-efi_loader-write-protocol-GUID-in-OpenProtocol.patch
git am ../patch/0001-efi_loader-debug-messages-for-protocol-interfaces.patch
git am ../patch/0001-efi_loader-switch-on-debug-in-efi_boottime.patch
