#!/bin/sh
git am ../patch/0001-efi_loader-rework-efi_locate_handle.patch
git am ../patch/0001-efi_loader-allow-return-value-in-EFI_CALL.patch
# git am ../patch/0001-efi_loader-efi_set_watchdog_timer-return-EFI_SUCCESS.patch

# Print GUIDs
git am ../patch/0001-Kconfig-add-option-to-build-with-fshort-wchar.patch
git am ../patch/0002-lib-add-some-utf16-handling-helpers.patch
git am ../patch/0003-vsprintf.c-add-UTF-16-string-ls-support.patch
git am ../patch/0004-vsprintf.c-add-GUID-printing.patch
git am ../patch/0005-examples-add-fallback-memcpy.patch

# EFI event services
git am ../patch/0001-efi_loader-notify-when-ExitBootServices-is-invoked.patch

# EFI console
# git am ../patch/0001-efi_loader-split-of-efi_cout_output_string_ext.patch
# git am ../patch/0001-efi_loader-write-reboot-reason.patch

# EFI protocol services
git am ../patch/0001-efi_loader-rework-efi_search_obj.patch
git am ../patch/0001-efi_loader-new-function-efi_search_protocol.patch
git am ../patch/0001-efi_loader-simplify-efi_install_protocol_interface.patch
git am ../patch/0001-efi_loader-simplify-efi_uninstall_protocol_interface.patch
git am ../patch/0001-efi_loader-open_info-in-OpenProtocol-CloseProtocol.patch
git am ../patch/0002-efi_loader-implement-OpenProtocolInformation.patch
git am ../patch/0001-efi_loader-non-static-efi_open_protocol-efi_close_pr.patch
git am ../patch/0001-efi_loader-pass-GUIDs-as-const-efi_guid_t.patch

git am ../patch/0001-efi_loader-write-protocol-GUID-in-OpenProtocol.patch
git am ../patch/0001-efi_loader-debug-messages-for-protocol-interfaces.patch
git am ../patch/0001-efi_loader-switch-on-debug-in-efi_boottime.patch

# git am ../patch/0001-efi_loader-define-EFI_PLATFORM_DRIVER_OVERRIDE_PROTO.patch
# git am ../patch/0001-efi_loader-define-EFI_DRIVER_FAMILY_OVERRIDE_PROTOCO.patch
git am ../patch/0001-efi_loader-implement-ConnectController.patch
