#!/bin/sh

# Reserved memory regions for Odroid C2
git am ../patch/0001-meson-gx-reserved-memory-regions.patch

# Enable debug messages in boottime services
git am ../patch/0001-efi_loader-switch-on-debug-in-efi_boottime.patch

# EFI event services
git am ../patch/0001-efi_loader-notify-when-ExitBootServices-is-invoked.patch

# EFI console
git am ../patch/0001-efi_loader-split-of-efi_cout_output_string_ext.patch
git am ../patch/0001-efi_loader-write-reboot-reason.patch

# EFI protocol services
git am ../patch/0001-efi_loader-implement-open-info.patch

